<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="APIMetamodel" nsURI="http://www.kowihan.com/APIMetamodel" nsPrefix="api">
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidPythonVersion ValidProjectName HasEntities ValidFramework"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidPythonVersion" value="self.pythonVersion.matches('3\.[7-9]|3\.1[0-2]')"/>
      <details key="ValidProjectName" value="not self.projectName.oclIsUndefined() and self.projectName.size() >= 3 and self.projectName.matches('[a-zA-Z_][a-zA-Z0-9_]*')"/>
      <details key="HasEntities" value="self.entities->size() >= 1"/>
      <details key="ValidFramework" value="Set{'DJANGO', 'FLASK', 'FASTAPI'}->includes(self.framework)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="framework" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pythonVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
        eType="#//Interaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//DatabaseConfig"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" eType="#//AuthenticationConfig"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apiFeatures" eType="#//APIFeatures"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidEntityName HasAttributes NoDuplicateAttributes ValidTableName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidEntityName" value="self.name.matches('[A-Z][a-zA-Z0-9_]*')"/>
      <details key="HasAttributes" value="self.attributes->size() >= 1"/>
      <details key="NoDuplicateAttributes" value="self.attributes->forAll(a1, a2 | a1 &lt;> a2 implies a1.name &lt;> a2.name)"/>
      <details key="ValidTableName" value="self.tableName.matches('[a-z][a-z0-9_]*')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//Index" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentEntity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidAttributeName PrimaryKeyNotNullable ValidTypeConstraints ValidDataType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidAttributeName" value="self.name.matches('[a-z][a-zA-Z0-9_]*')"/>
      <details key="PrimaryKeyNotNullable" value="self.isPrimaryKey implies not self.isNullable"/>
      <details key="ValidTypeConstraints" value="(self.type = 'STRING' and self.maxLength > 0) implies self.maxLength &lt;= 5000"/>
      <details key="ValidDataType" value="Set{'STRING', 'TEXT', 'INTEGER', 'FLOAT', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATETIME', 'TIME', 'UUID', 'EMAIL', 'URL', 'JSON'}->includes(self.type)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="helpText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidRelationshipName ValidTarget ValidCascadeBehavior ValidRelationType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidRelationshipName" value="self.name.matches('[a-z][a-zA-Z0-9_]*')"/>
      <details key="ValidTarget" value="not self.targetEntity.oclIsUndefined() and self.targetEntity.size() > 0"/>
      <details key="ValidCascadeBehavior" value="Set{'CASCADE', 'SET_NULL', 'PROTECT'}->includes(self.onDelete)"/>
      <details key="ValidRelationType" value="Set{'ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_ONE', 'MANY_TO_MANY'}->includes(self.type)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetEntity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relatedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onDelete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidOperationName ValidVisibility ValidReturnType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidOperationName" value="self.name.matches('[a-z][a-zA-Z0-9_]*')"/>
      <details key="ValidVisibility" value="Set{'PUBLIC', 'PRIVATE', 'PROTECTED'}->includes(self.visibility)"/>
      <details key="ValidReturnType" value="not self.returnType.oclIsUndefined() and self.returnType.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidParameterName ValidParameterType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidParameterName" value="self.name.matches('[a-z][a-zA-Z0-9_]*')"/>
      <details key="ValidParameterType" value="not self.type.oclIsUndefined() and self.type.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidIndexName HasFields ValidIndexConfiguration"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidIndexName" value="self.name.matches('[a-z][a-z0-9_]*')"/>
      <details key="HasFields" value="self.fields->size() >= 1"/>
      <details key="ValidIndexConfiguration" value="self.fields->forAll(f | not f.oclIsUndefined() and f.size() > 0)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fields" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidInteractionName ValidHTTPMethod HasParticipants ValidEndpoint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidInteractionName" value="self.name.matches('[A-Z][a-zA-Z0-9_]*')"/>
      <details key="ValidHTTPMethod" value="Set{'GET', 'POST', 'PUT', 'PATCH', 'DELETE'}->includes(self.httpMethod)"/>
      <details key="HasParticipants" value="self.participants->size() >= 2"/>
      <details key="ValidEndpoint" value="self.endpoint.startsWith('/') and self.endpoint.matches('/[a-zA-Z0-9_/-]*')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useCaseDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Participant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidParticipantName ValidActorType ValidEntityReference"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidParticipantName" value="self.name.matches('[A-Z][a-zA-Z0-9_]*')"/>
      <details key="ValidActorType" value="Set{'ACTOR', 'ENTITY', 'SYSTEM', 'EXTERNAL'}->includes(self.actorType)"/>
      <details key="ValidEntityReference" value="self.actorType = 'ENTITY' implies (not self.entityName.oclIsUndefined() and self.entityName.size() > 0)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidSequenceNumber ValidMessageType ValidParticipants ValidOperation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidSequenceNumber" value="self.sequenceNumber > 0"/>
      <details key="ValidMessageType" value="Set{'SYNCHRONOUS', 'ASYNCHRONOUS', 'REPLY', 'CREATE'}->includes(self.messageType)"/>
      <details key="ValidParticipants" value="self.fromParticipant &lt;> self.toParticipant"/>
      <details key="ValidOperation" value="not self.operation.oclIsUndefined() and self.operation.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromParticipant" eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toParticipant" eType="#//Participant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseConfig">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidDatabaseType ValidPort ValidDatabaseName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidDatabaseType" value="Set{'POSTGRESQL', 'MYSQL', 'SQLITE', 'MONGODB'}->includes(self.type)"/>
      <details key="ValidPort" value="self.port > 0 and self.port &lt;= 65535"/>
      <details key="ValidDatabaseName" value="not self.name.oclIsUndefined() and self.name.size() > 0 and self.name.matches('[a-zA-Z_][a-zA-Z0-9_]*')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationConfig">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidAuthMethod ValidTokenExpiry"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidAuthMethod" value="Set{'JWT', 'SESSION', 'OAUTH2', 'BASIC'}->includes(self.method)"/>
      <details key="ValidTokenExpiry" value="self.tokenExpiryMinutes >= 5 and self.tokenExpiryMinutes &lt;= 10080"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenExpiryMinutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIFeatures">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="invariants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidFeatureCombination"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidFeatureCombination" value="self.swagger implies self.corsEnabled"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pagination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filtering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swagger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="corsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
